### ISSUE TITLE
Returning Empty Object

### ISSUE THREAD

**Issue by gkodikara** [pcel/meteor-serialize#1]
Hi

I've tried implementing this but when I run it as instructed I only get an empty object {}.
I'm using a bootstrap form with structure similar to -

    <form class="form-horizontal">
    <fieldset><div class="form-group" data-type="text">

          
          <label class="col-md-4 control-label" for="input01">Text input</label>
          <div class="col-md-4">
            <input type="text" placeholder="placeholder" class="form-control input-md">
            <p class="help-block">Supporting help text</p>
          </div>
        </div>

    </fieldset>
    </form>
Any idea why?

Thanks for any help.

**Comment by kotchuprik** [comment]
Your html input doesn't has "name". Check again with name attribute.

**Comment by jgdovin** [comment]
I am having the same issue:

    <template name="myForm" id="myForm">
    <form action="#">
        <input type="text" name="name" placeholder="Name"/><br/>
        <input type="text" name="email" placeholder="Email"/><br/>
        <input type="text" name="foo" placeholder="Foo"/><br/>
        <input type="submit" value="Save"/>
    </form>
</template>

and my js:

    if(Meteor.isClient) {

    Template.myForm.events({
        "submit form" : function(event, template) {
            event.preventDefault();
            console.log(template.$('#myForm').serializeJSON());
            console.log($('#myForm').serializeJSON());
            console.log(event.target.serializeJSON());
        }
    });

}

first two return empty object, third one returns not a function

**Comment by jpmx** [comment]
#### Template:
```html
<template name="myForm">
  <form action="#" class="myFormCssSelector" id="myFormIDSelector">
    <input type="text" name="name" placeholder="Name"/><br/>
    <input type="text" name="email" placeholder="Email"/><br/>
    <input type="text" name="foo" placeholder="Foo"/><br/>
    <input type="button" class="mySubmitButton" value="Save"/>
  </form>
</template>
```

#### JavaScript
```js
Template.myForm.events({
    "click .mySubmitButton" : function(event) {
        console.log( $('.myFormCssSelector').serializeJSON() );
        console.log( $('#myFormIDSelector').serializeJSON() );
        console.log( $(event.target.form).serializeJSON() );
    }
});
```

[See full example](https://github.com/pcel/meteor-serialize/tree/master/example)
